// angular/examenangularemq/src/app/components/menu/menu.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';
import { Nacionalidad } from 'src/app/models/nacionalidad';
import { ServicePeliculas } from 'src/app/services/pelicula.service';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css']
})
export class MenuComponent implements OnInit {

  @ViewChild("cajaBusqueda") cajaBusqueda! : ElementRef;
  @ViewChild("selectGenero") selectGenero! : ElementRef;
  @ViewChild("selectNacionalidad") selectNacionalidad! : ElementRef;
  public nacionalidades! : Array<Nacionalidad>;
  public generos! : Array<any>;

  constructor(
    private _service : ServicePeliculas ,
    private _router : Router
  ) { }

  ngOnInit(): void {
    this.cargarNacionalidades();
    this.cargarGeneros();
  }

  cargarNacionalidades (){
    this._service.getNacionalidades().subscribe(res => {
      this.nacionalidades = res;
      for(var i = 0 ; i< this.nacionalidades.length; i++) {
        console.log(this.nacionalidades[i].bandera)
      }
    });
  }

  cargarGeneros () {
    this._service.getGeneros().subscribe(res => {
      this.generos = res;
    });
  }

  peliculasNacionalidad() {    
    this._router.navigate(["/peliculas", this.selectNacionalidad.nativeElement.value, "n"])
  }

  peliculasGenero() {    
    this._router.navigate(["/peliculas", this.selectGenero.nativeElement.value, "g"])
  }

  buscarPeliculas() {
    this._router.navigate(['busquedapeliculas',this.cajaBusqueda.nativeElement.value]);
  }

}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li> 
          <select (change)="peliculasNacionalidad()" class="form-select" 
          name="selectNacionalidad" #selectNacionalidad>
              <option *ngFor="let n of nacionalidades" 
              value="{{n.idNacionalidad}}"
              style="background-image: url(n.bandera);">
                {{n.nombre}}                 
              </option>
          </select>
          <select (change)="peliculasGenero()" class="form-select" 
          name="selectGenero" #selectGenero>
            <option *ngFor="let g of generos" value="{{g.idGenero}}">
                {{g.nombre}}                
            </option>
        </select>
        <form #formBusqueda="ngForm" class="d-flex">
            <input class="form-control me-2" type="text" 
            placeholder="Titulo" aria-label="Search"
            name="cajaBusqueda" #cajaBusqueda>
            <button class="btn btn-outline-success"
            (click)="buscarPeliculas()"
            >Buscar</button>
          </form>
        </ul>    
      </div>
    </div>
</nav>

// vue/examenvueemq/src/components/Menu.vue
<template>
    <div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
            <a class="navbar-brand" to="/">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">                    
                    <router-link class="nav-link active" aria-current="page" to="/">Home</router-link>
                </li>
                 <select v-on:change="peliculasGenero()" class="form-select" 
                    name="selectGeneros" v-model="genero">
                        <option v-for="(g, index) in generos" :key="index" :value="g.idGenero">
                            <p>{{g.nombre}}</p>                            
                        </option>
                    </select>   
                    <select class="form-select" 
                    name="selectNacionalidad" v-model="nacionalidad"  v-on:change="peliculasNacionalidad()">
                        <option v-for="(n, index) in nacionalidades" :key="index" :value="n.idNacionalidad">
                            <p>{{n.nombre}}</p>
                            <img :src="n.bandera" alt="bandera"/>
                        </option>
                    </select>             
                </ul>  
                <form v-on:submit.prevent="buscarPeli()" class="d-flex">
                    <input class="form-control me-2" 
                    type="text" placeholder="Titulo" 
                    aria-label="Search" v-model="pelicula">
                    <button class="btn btn-outline-success" 
                    type="submit">Buscar</button>
                </form>  
            </div>
            </div>
        </nav>
    </div>
</template>

<script>
import ServicePeliculas from './../services/ServicePeliculas';

const service = new ServicePeliculas();
export default {
    name : "Menu" , 
    data () {
        return {
            generos : [] , 
            nacionalidades : [] ,
            genero : 0 ,
            nacionalidad : 0 , 
            pelicula : ""
        }
    }, mounted() {
        this.cargarGeneros();
        this.cargarNacionalidades();
    } , methods : {
        cargarGeneros() {
            service.getGeneros().then(res => {
                this.generos = res;
            })
        } , cargarNacionalidades() {            
            service.getNacionalidades().then(res => {
                this.nacionalidades = res;
            })
        } , peliculasGenero() {            
            this.$router.push("/peliculas/" + this.genero + "/g");
        } , peliculasNacionalidad() {
            this.$router.push("/peliculas/" + this.nacionalidad + "/n")
        } , buscarPeli() {
            this.$router.push("/busquedapeliculas/" + this.pelicula)
        }
    }
}
</script>
