// angular/examenangularemq/src/app/components/peliculas/peliculas.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Params } from '@angular/router';
import { Pelicula } from 'src/app/models/pelicula';
import { ServicePeliculas } from 'src/app/services/pelicula.service';

@Component({
  selector: 'app-peliculas',
  templateUrl: './peliculas.component.html',
  styleUrls: ['./peliculas.component.css']
})
export class PeliculasComponent implements OnInit {

  public peliculas! : Array<Pelicula>;
  public peliculaDetalles! : Pelicula;
  public peliculaDetallesMostrar : boolean;
  public generoNacionalidad! : string;

  constructor(
    private _route : ActivatedRoute ,
    private _service : ServicePeliculas
  ) { 
    this.peliculaDetallesMostrar = false;
  } 

  ngOnInit(): void {
   this.cargarPelis();
  }

  cargarPelicula(index : number) {
    this.peliculaDetallesMostrar = true;
    this.peliculaDetalles = this.peliculas[index];
  }

  cargarPelis() {
    console.log("cargo pelis")
   
    this._route.params.subscribe((params : Params) => {
      if (params['genenacio'] == "g") {
          this._service.getPeliculasGenero(params['id']).subscribe(res => {
            this.peliculaDetallesMostrar = false            
            this.generoNacionalidad = "g";
            this.peliculas = res;
          });
      } else if (params['genenacio'] == "n") {
          this._service.getPeliculasNacionalidad(params['id']).subscribe(res => {            
            this.peliculaDetallesMostrar = false
            this.generoNacionalidad = "n";
            this.peliculas = res;
          });
      }
    });
  }


}


<div *ngIf="peliculas">    
   
    <table class="table table-dark">
        <thead>
            <tr>
                <th>PELICULA</th>
                <th>DETALLES</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let p of peliculas; let i = index">
                <th>{{p.titulo}}</th>
                <th>
                    <button (click)="cargarPelicula(i)" class="btn btn-danger">
                        Detalles
                    </button>
                </th>
            </tr>
        </tbody>
    </table>
</div>
<div *ngIf="peliculaDetallesMostrar">
    <app-pelicula 
    [peliculaDetalles]="peliculaDetalles"
    [generoNacionalidad]="generoNacionalidad"
    (cargarPelis)="cargarPelis()"></app-pelicula>
</div>
<div *ngIf="peliculas == null">
    <h1>Loading...</h1>
</div>

// vue/examenvueemq/src/components/Peliculas.vue
<template>
    <div>                         
        <div v-if="peliculas.length > 0">               
            <table class="table table-dark">
                <thead>
                    <tr>
                        <th>PELICULA</th>
                        <th>DETALLES</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="(p,index) in peliculas" :key="index">
                        <th>{{p.titulo}}</th>
                        <th>
                            <button v-on:click="cargarPelicula(index)" class="btn btn-danger">
                                Detalles
                            </button>
                        </th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div v-else>
            <h1>Loading...</h1>
        </div>

        <div v-if="peliculaDetallesMostrar">            
            <Pelicula :peliculaDetalles="peliculaDetalles"
            :generoNacionalidad="generoNacionalidad"
            v-on:cargarPeliculas="cargarPeliculas" />
        </div>

    </div>
</template>
<script>
import ServicePeliculas from './../services/ServicePeliculas';
import Pelicula from './Pelicula.vue';

const service  = new ServicePeliculas();
export default {
    name : "Peliculas" , 
    components : {
        Pelicula
    } , 
    data() {
        return {
            peliculas : [] , 
            peliculaDetalles : null , 
            peliculaDetallesMostrar : false , 
            generoNacionalidad : ""
        }
    } , mounted() {
        this.cargarPeliculas();
    } , methods : {
        cargarPeliculas() {
            this.peliculaDetallesMostrar = false;
            this.peliculas = [];
            if (this.$route.params.genenacio == "g") {
                this.generoNacionalidad = "g";
                service.getPeliculasGenero(this.$route.params.id).then(res => {
                    this.peliculas = res;
                });
            } else if (this.$route.params.genenacio == "n") {
                this.generoNacionalidad = "n";
                service.getPeliculasNacionalidad(this.$route.params.id).then(res => {
                    this.peliculas = res;
                });
            }
        } , cargarPelicula(index) {
            this.peliculaDetallesMostrar = true;
            this.peliculaDetalles = this.peliculas[index];
        }
    } , watch: {
        '$route.params.id'(nextVal, prevVal){
            if (nextVal != prevVal){
                this.cargarPeliculas();            
            }
        } , '$route.params.genenacio'(nextVal, prevVal){
            if (nextVal != prevVal){
                this.cargarPeliculas();            
            }
        }
    }

}
</script>
