// angular/examenangularemq/src/app/components/pelicula/pelicula.component.ts
import { Component, ElementRef, Input, OnInit, Output, ViewChild, EventEmitter } from '@angular/core';
import { Router } from '@angular/router';
import { Genero } from 'src/app/models/genero';
import { Pelicula } from 'src/app/models/pelicula';
import { ServicePeliculas } from 'src/app/services/pelicula.service';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';
import { Nacionalidad } from 'src/app/models/nacionalidad';


@Component({
  selector: 'app-pelicula',
  templateUrl: './pelicula.component.html',
  styleUrls: ['./pelicula.component.css']
})
export class PeliculaComponent implements OnInit {

  @Input() peliculaDetalles! : Pelicula;
  public generos! : Array<Genero>;
  @ViewChild("selectGenero") selectGenero! : ElementRef;
  @Output() cargarPelis: EventEmitter<any> = new EventEmitter();
  @Input() generoNacionalidad! : string  ;
  public genero! : Genero;
  public nacionalidad! : Nacionalidad

  constructor(
    private _service : ServicePeliculas ,    
    private _sanitizer: DomSanitizer

  ) { }

  ngOnInit(): void {
    this.cargarGeneros();
    this.cargarGeneroNacionalidad();
    this.getVideoIframe(this.peliculaDetalles.enlaceVideo);
  }

  cargarGeneroNacionalidad() {
    if (this.generoNacionalidad == "g") {
      var idGenero = this.peliculaDetalles.idGenero.toString();
        this._service.getGenero(idGenero).subscribe(res => {
          this.genero = res;
        })
    } else if(this.generoNacionalidad == "n") {
      var idNacionalidad = this.peliculaDetalles.idNacionalidad.toString()
       this._service.getNacionalidad(idNacionalidad).subscribe( res => {
         this.nacionalidad = res;
         console.log("Hay nacionalid")
       })
    }
}

  cargarGeneros () {
    this._service.getGeneros().subscribe(res => {
      this.generos = res;
    });
  }

  cambiarPeliGenero() {
    var idpeli = this.peliculaDetalles.idPelicula.toString();
      this._service.putPeliGenero(
        idpeli,
        this.selectGenero.nativeElement.value).subscribe(res => {
          alert("Se ha cambiado correctamente")          
          this.cargarPelis.emit();
      })
  }

  eliminarPeli(idpeli : number) {
    if (window.confirm("¿Seguro que quiere eliminarla?")) {
      console.log("Se elimina la peli " + idpeli)
      alert("Se ha eliminado correctamete")
      var idPeliString = this.peliculaDetalles.idPelicula.toString();
      this._service.deletePelicula(idPeliString).subscribe(res => {
        this.cargarPelis.emit();
      });
    } else {
      console.log("No se elimina")
    }
  }

  getVideoIframe(url:string) {
    var video, results;

    if (url === null) {
        return '';
    }
    results = url.match('[\\?&]v=([^&#]*)');
    video   = (results === null) ? url : results[1];
 
    return this._sanitizer.bypassSecurityTrustResourceUrl('https://www.youtube.com/embed/' + video);   
}

}

<div *ngIf="peliculaDetalles">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="card" style="width:100%;">
        <img src="{{peliculaDetalles.foto}}" style="width: 300px;" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{peliculaDetalles.titulo}}</h5>
          <p class="card-text">{{peliculaDetalles.argumento}}</p>
          <div *ngIf="genero">
            <h5 class="card-title">GENERO: {{genero.nombre}}</h5>
          </div>
          <div *ngIf="nacionalidad">
              <h5 class="card-title">NACIONALIDAD: {{nacionalidad.nombre}}</h5>
          </div>

          <h5 class="mt-2 mb-2 text-warning card-title">Cambiar genero</h5>
          <select (change)="cambiarPeliGenero()" *ngIf="generos" class="form-select" 
          name="selectGenero" #selectGenero>
            <option *ngFor="let g of generos" value="{{g.idGenero}}">
                {{g.nombre}}            
            </option>
          </select> 
          <button (click)="eliminarPeli(peliculaDetalles.idPelicula)" class="m-2 btn btn-danger">
            Eliminar
          </button>
          <p>
            <iframe width="560" height="315" [src]="getVideoIframe(peliculaDetalles.enlaceVideo)" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </p>            
        </div>
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

// vue/examenvueemq/src/components/Pelicula.vue
<template>
    <div>     
        <div v-if="peliculaDetalles">
            <div class="row">
                <div class="col-md-2"></div>
                    <div class="col-md-8">
                        
                        <div class="card" style="width: 100%;">
                        <img :src="peliculaDetalles.foto" style="width:300px;" class="card-img-top" alt="foto peli">
                            <div class="card-body">
                                <h5 class="card-title">{{peliculaDetalles.titulo}}</h5>
                                <p class="card-text">{{peliculaDetalles.argumento}}</p>                                    
                                <div v-if="generoPelicula">
                                    <h5 class="card-title">GENERO: {{generoPelicula.nombre}}</h5>
                                </div>
                                 <div v-if="nacionalidadPelicula">
                                    <h5 class="card-title">NACIONALIDAD: {{nacionalidadPelicula.nombre}}</h5>
                                </div>
                                <h5 class="mt-2 mb-2 text-warning card-title">Cambiar genero</h5>                                
                                <select v-on:change="cambiarPeliGenero" v-if="generos" class="form-select" 
                                name="selectGenero" v-model="selectGenero">
                                    <option v-for="(g,index ) in generos" :key="index"
                                    :value="g.idGenero">
                                        {{g.nombre}}            
                                    </option>
                                </select> 
                                <button v-on:click="eliminarPeli(peliculaDetalles.idPelicula)" class="m-2 btn btn-danger">
                                    Eliminar
                                </button>
                            </div>
                            <iframe width="560" height="315" 
                            
                            v-bind:src="'https://www.youtube.com/embed/' + peliculaDetalles.enlaceVideo" 
                            frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        </div>                                      
                    </div>
                <div class="col-md-2"></div>
            </div>
        </div>
    </div>
</template>

<script>
import ServicePeliculas from './../services/ServicePeliculas';

const service  = new ServicePeliculas();
export default {
    name : "Pelicula" , 
    props: ["peliculaDetalles","generoNacionalidad"] ,
    data() {
        return {
            generos : [] ,
            selectGenero : 0,
            generoPelicula : null , 
            nacionalidadPelicula : null
        }
    } , methods : {
        cargarGeneros() {
            service.getGeneros().then(res => {
                this.generos = res;
            });
        } , cambiarPeliGenero() {
            service.putPeliGenero(this.peliculaDetalles.idPelicula, this.selectGenero).then(res => {
                alert("Se ha cambiado correctamente")
                console.log(res);
                this.$emit("cargarPeliculas");    
            })
        } , eliminarPeli(idpeli) {
            if (window.confirm("¿Seguro que quiere eliminarla?")) {
                console.log("Se elimina la peli " + idpeli)
                service.deletePelicula(idpeli).then(res => {
                    console.log(res);
                    this.$emit("cargarPeliculas");    
                });
                
            } else {
                console.log("No se elimina");
            }
        } , cargarGeneroNacionalidad() {
            if (this.generoNacionalidad == "g") {
                service.getGenero(this.peliculaDetalles.idGenero).then(res => {
                    this.generoPelicula = res;
                });
            } else if(this.generoNacionalidad == "n") {
                service.getNacionalidad(this.peliculaDetalles.idNacionalidad).then(res => {
                    this.nacionalidadPelicula = res;
                });
            }
        }
    } , mounted() {
        this.cargarGeneros();

        this.cargarGeneroNacionalidad();
    }
}
</script>
